version: 2
project_name: noxmem

before:
  hooks:
    - go mod tidy

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

nfpms:
  - package_name: noxmem
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: "https://github.com/crumbyte/noxmem"
    description: "Terminal utility for live GoLang heap memory profiling."
    maintainer: crumbyte <oleksiivodotyiets@gmail.com>
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    contents:
      # man page
      - src: ./man/noxmem.1
        dst: /usr/share/man/man1/noxmem.1
      # docs
      - src: ./LICENSE
        dst: /usr/share/doc/noxmem/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/noxmem/README.md

builds:
  - id: noxmem
    binary: noxmem
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [ tar.gz ]
    name_template: >-
      {{ .ProjectName }}-
      {{- .Tag -}}-
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip ]
    files:
      - LICENSE*
      - README*
      - man/*

homebrew_casks:
  - name: noxmem
    binary: noxmem
    manpages:
      - man/noxmem.1
    directory: Casks
    homepage: "https://github.com/crumbyte/noxmem"
    description: "Terminal utility for live GoLang heap memory profiling."
    skip_upload: auto
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxmem"]
          end
    repository:
      owner: crumbyte
      name: homebrew-noxmem
      branch: main
      token: "{{ .Env.GH_PAT }}"
  - name: noxmem-nightly
    binary: noxmem
    manpages:
      - man/noxmem.1
    directory: Casks
    homepage: "https://github.com/crumbyte/noxmem"
    description: "Nightly build of the terminal utility for live GoLang heap memory profiling."
    skip_upload: '{{ not (contains .Tag "nightly") }}'
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxmem"]
          end
    repository:
      owner: crumbyte
      name: homebrew-noxmem
      branch: main
      token: "{{ .Env.GH_PAT }}"

scoops:
  - name: noxmem
    homepage: "https://github.com/crumbyte/noxmem"
    description: "Terminal utility for live GoLang heap memory profiling."
    license: MIT
    skip_upload: auto
    repository:
      owner: crumbyte
      name: scoop-bucket
      branch: main
      token: "{{ .Env.GH_PAT }}"
  - name: noxmem-nightly
    homepage: "https://github.com/crumbyte/noxmem"
    description: "Nightly build of the terminal utility for visualizing file system usage."
    license: MIT
    skip_upload: '{{ not (contains .Tag "nightly") }}'
    repository:
      owner: crumbyte
      name: scoop-bucket
      branch: main
      token: "{{ .Env.GH_PAT }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "README.MD"
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  github:
    owner: crumbyte
    name: noxmem
  name_template: '{{.ProjectName}}-{{ if eq .Tag "nightly" }}nightly{{ else }}v{{.Version}}{{ end }}'
